
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: db_gimnasio
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - gimnasio-network
    restart: unless-stopped

  eureka-server:
    build: ./eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - gimnasio-network
    restart: always

  gateway-service:
    build: ./gimnasio
    container_name: gateway-service
    ports:
      - "8090:8090"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - gimnasio-network

  clase-service:
    build: ./clase
    container_name: clase-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/db_gimnasio
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - gimnasio-network

  entrenador-service:
    build: ./entrenador
    container_name: entrenador-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/db_gimnasio
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - gimnasio-network

  horario-service:
    build: ./horario
    container_name: horario-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/db_gimnasio
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - gimnasio-network

  socio-service:
    build: ./socio
    container_name: socio-service
    ports:
      - "8084:8084" 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/db_gimnasio
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - gimnasio-network

  rutina-service:
    build: ./rutina
    container_name: rutina-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/db_gimnasio
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - gimnasio-network

  inventario-service:
    build: ./inventario
    container_name: inventario-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/db_gimnasio
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - gimnasio-network

  notificacion-service:
    build: ./notificacion
    container_name: notificacion-service
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/db_gimnasio
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - gimnasio-network

  pago-service:
    build: ./pago
    container_name: pago-service
    ports:
      - "8088:8088"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/db_gimnasio
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - gimnasio-network

  registroacceso-service:
    build: ./registroacceso
    container_name: registroacceso-service
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/db_gimnasio
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - gimnasio-network

  plansuscripcion-service:
    build: ./plansuscripcion
    container_name: plansuscripcion-service
    ports:
      - "8091:8091" 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/db_gimnasio
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - gimnasio-network

# Red interna unificada
networks:
  gimnasio-network:
    driver: bridge